name = "Bold"
license = "GNU3.0"
licenselink = "https://github.com/deletescape/bold-theme/blob/master/LICENSE.md"
description = "Clean, responsive one-page portfolio accompanied by a minimalist blog."
homepage = "https://github.com/deletescape/bold-theme"
tags = ["blog", "portfolio", "gallery", "minimalist", "responsive", "flexbox"]
features = ["blog", "portfolio", "google analytics"]
min_version = 0.24.1

[author]
    name = "Toma Nistor"
    homepage = "https://tomanistor.com"
